[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run db:generate && npm run build"

[deploy]
startCommand = "npm run db:deploy && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
